# Generated by Django 4.1 on 2023-04-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="photography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("lengend", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("picture", models.CharField(max_length=100)),
            ],
        ),
    ]
