# Generated by Django 4.1 on 2023-04-20 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photography",
            old_name="lengend",
            new_name="legend",
        ),
    ]
