# Generated by Django 4.1 on 2023-05-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0007_photography_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photography",
            name="published",
            field=models.BooleanField(default=True),
        ),
    ]
