# Generated by Django 4.1 on 2023-04-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0002_rename_lengend_photography_legend"),
    ]

    operations = [
        migrations.AddField(
            model_name="photography",
            name="category",
            field=models.CharField(
                choices=[
                    ("NEBULOSA", "Nebulosa"),
                    ("ESTRELA", "Estrela"),
                    ("GALÁXIA", "Galáxia"),
                    ("PLANETA", "Planeta"),
                ],
                default="",
                max_length=100,
            ),
        ),
    ]
