# Generated by Django 4.1 on 2023-04-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0003_photography_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="photography",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
